sudo: required
os: linux
dist: bionic
services:
  - docker
install: true
stages:
  - shell check
  - build docker images

before_script:
  - sleep 15
  - sudo apt-get install -y curl shellcheck
  - docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
  - docker buildx create --name multiarch --driver docker-container --use
  - docker buildx inspect --bootstrap
  #Upgrade to Docker CE 19.03 for BuildKit support
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  # Show info to simplify debugging and create a builder
  - docker info
  - docker buildx create --name builder --use
  - docker buildx ls
jobs:
  include:

    - stage: shell check
      name: checking syntax of shell script
      script:
      - bash -c 'shopt -s globstar nullglob; shellcheck **/*.{sh,ksh,bash}' || true

    - stage: build docker images
      name: build docker image byoc
      env: GOARCH=amd64
      script:
      - make build-byoc
    
    - stage: build docker images
      name: build docker image litmus-python
      script:
      - make build
      - make build-litmus-python

notifications:
  email:
    recipients:
      - karthik.s@mayadata.io
      - sumit_nagal@intuit.com
