os: linux
dist: bionic
services:
  - docker
install: true
stages:
  - shell check
  - build docker images
  - push docker images

before_script:
  - sudo apt-get install -y curl shellcheck
  - docker run --rm --privileged docker/binfmt:a7996909642ee92942dcd6cff44b9b95f08dad64
  # #Upgrade to Docker CE 19.03 for BuildKit support
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce=5:19.03.8~3-0~ubuntu-bionic # pin version for reproducibility
  # Show info to simplify debugging and create a builder
  - docker info
  - docker buildx create --name builder --use
  - docker buildx ls
jobs:
  include:

    - stage: shell check
      name: checking syntax of shell script
      script:
      - bash -c 'shopt -s globstar nullglob; shellcheck **/*.{sh,ksh,bash}' || true
    
    - stage: build docker images
      name: installing and configuring dependencies
      script:
      - make deps
    
    - stage: build docker images
      name: build docker image
      script:
      - make build

    - stage: push docker images
      name: push docker images
      script:
      - make push

notifications:
  email:
    recipients:
      - karthik.s@mayadata.io
      - sumit_nagal@intuit.com
