dist: trusty
sudo: required
install: true
stages:
  - shell check
  - build docker images
before_install:
  - sleep 15
  - sudo apt-get install -y curl shellcheck

jobs:
  include:

    - stage: shell check
      name: checking syntax of shell script
      script:
      - bash -c 'shopt -s globstar nullglob; shellcheck **/*.{sh,ksh,bash}' || true

    - stage: build docker images
      name: build docker image byoc
      env: GOARCH=amd64
      script:
      - make build-byoc
    
    - stage: build docker images
      name: build docker image litmus-python
      script:
      - make build
      - make build-litmus-python

notifications:
  email:
    recipients:
      - karthik.s@mayadata.io
      - sumit_nagal@intuit.com
